baseURL = "https://rathish.netlify.app/"
languageCode = "en-us"
title = ""
theme = "PaperMod"

[params]
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  mainSections = ["posts"]
  defaultTheme = "auto"
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true

  [params.profileMode]
    enabled = true
    title = "Hey, I'm Subramanyam 👋"
    subtitle = "Most people call me Rathish. I’m a software engineer, and this is my little corner of the internet where I share my travels, photography, and whatever else sparks my curiosity. ✨"
    imageUrl = "/images/profile/me.png"
    imageWidth = 200
    imageHeight = 200
    imageTitle = "Rathish"
    buttons = [
      { name = "Travel", url = "/travel" },
      { name = "Photography", url = "/about" },
    ]

  [params.list]
    layout = "cards"  # Options: list, cards, compact

[params.homeInfoParams]
  Title = "👋 Welcome"
  Content = """
Hi, I’m Subramanyam — but most people call me Rathish. I’m a software engineer, and this is my little corner of the internet where I share my travels, photography, and whatever else sparks my curiosity. ✨
"""

[[params.socialIcons]]
name = "github"
url = "https://github.com/imRathish"

[[params.socialIcons]]
name = "linkedin"
url = "https://linkedin.com/in/subramanyam-s-s-11252313b"


[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
